sudo : required
services:
  - docker

before_install:
  - docker build -t pb2323/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true pb2323/react-test npm test

after_success:
  - docker build -t pb2323/multi-client ./client
  - docker build -t pb2323/multi-worker ./worker
  - docker build -t pb2323/multi-nginx ./nginx
  - docker build -t pb2323/multi-server ./server
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push pb2323/multi-client
  - docker push pb2323/multi-worker
  - docker push pb2323/multi-nginx
  - docker push pb2323/multi-server

deploy:
  edge: true
  provider: "elasticbeanstalk"
  region: "ap-south-1"
  app: "multi-docker"
  env: "Multidocker-env-1"
  bucket_name: "elasticbeanstalk-ap-south-1-324131767317"	
  bucket_path: "docker-multi"
  on: 
    branch: "master"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY