sudo : required
services:
  - docker

before_install:
  - docker build -t pb2323/react-test -f ./client/Dockerfile.dev

script:
  - docker run -e CI=true pb2323/react-test npm test

after_success:
  - docker build -t pb2323/multi-client ./client
  - docker build -t pb2323/multi-worker ./worker
  - docker build -t pb2323/multi-nginx ./nginx
  - docker build -t pb2323/multi-server ./server
